# Update versions with: pre-commit autoupdate
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
        args:
        - "--fix"
        - "--show-fixes"
       # Run the formatter.
      - id: ruff-format

  # Add mypy for static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-toml"]